# Generated by Django 2.2.1 on 2019-05-26 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('code', models.CharField(max_length=255, verbose_name='代码')),
            ],
            options={
                'verbose_name': '指数',
                'verbose_name_plural': '指数',
            },
        ),
        migrations.CreateModel(
            name='IndexList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='数值')),
                ('pe', models.FloatField(verbose_name='市盈率')),
                ('target', models.FloatField(null=True, verbose_name='PE标杆')),
                ('act', models.IntegerField(choices=[(1, '买入'), (3, '保持'), (2, '卖出')], default=0, verbose_name='行动')),
                ('summary', models.CharField(max_length=1000, null=True, verbose_name='小结')),
                ('create_date', models.DateField(verbose_name='日期')),
                ('create_by', models.ForeignKey(default='user.User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Index', verbose_name='指数')),
            ],
            options={
                'verbose_name': '指数记录',
                'verbose_name_plural': '指数记录',
            },
        ),
    ]
