# Generated by Django 2.2.1 on 2019-05-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexlist',
            name='act',
            field=models.IntegerField(choices=[(1, '买入'), (2, '卖出'), (3, '保持')], null=True, verbose_name='行动'),
        ),
    ]
