# Generated by Django 2.2.1 on 2019-05-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20190526_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexlist',
            name='act',
            field=models.IntegerField(blank=True, choices=[(1, '买入'), (3, '保持'), (2, '卖出')], null=True, verbose_name='行动'),
        ),
        migrations.AlterField(
            model_name='indexlist',
            name='summary',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='小结'),
        ),
        migrations.AlterField(
            model_name='indexlist',
            name='target',
            field=models.FloatField(blank=True, null=True, verbose_name='PE标杆'),
        ),
    ]
