# Generated by Django 2.2.1 on 2019-05-30 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20190526_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexlist',
            name='act',
            field=models.IntegerField(blank=True, choices=[(1, '买入'), (2, '卖出'), (3, '保持')], null=True, verbose_name='行动'),
        ),
    ]
